/**
 * IOI 2026 contestants grouped by team, from https://stats.ioinformatics.org/contestants/2026.
 * Generated by scripts/gen-ioi-contestants.ts — do not edit by hand.
 */
export type IoiTeam = { team: string; country: string | null; members: string[] };

export const IOI_TEAMS: IoiTeam[] = [
  {
    "team": "Albania",
    "country": "AL",
    "members": [
      "Amir Kovaçi",
      "Boris Braho",
      "Skerdilaid Bilibashi"
    ]
  },
  {
    "team": "Algeria",
    "country": "DZ",
    "members": [
      "Fares Khelif",
      "Haithem Djefel",
      "Kian Abolghasemi",
      "Omar Abdelkafi Ykerlef"
    ]
  },
  {
    "team": "Argentina",
    "country": "AR",
    "members": [
      "Ariel Lerner",
      "Bianca Vicente",
      "Juan José Läderach",
      "Nicolás Faggi"
    ]
  },
  {
    "team": "Armenia",
    "country": "AM",
    "members": [
      "Aleks Grigoryan",
      "Tigran Matsakyan",
      "Vahagn Gyozalyan",
      "Vahan Abrahamyan"
    ]
  },
  {
    "team": "Australia",
    "country": "AU",
    "members": [
      "Justin Goh",
      "Matthew Shi Xuan Lin",
      "Nathan Zhou",
      "Philip Liu"
    ]
  },
  {
    "team": "Austria",
    "country": "AT",
    "members": [
      "André Tremetsberger",
      "Arash Jafarian",
      "Julian Mejatsch",
      "Manuel Zöttl"
    ]
  },
  {
    "team": "Azerbaijan",
    "country": "AZ",
    "members": [
      "Ahmad Gambarli",
      "Akbar Ahmadov",
      "Elay Verdiyev",
      "Hasan Valiyev"
    ]
  },
  {
    "team": "Bangladesh",
    "country": "BD",
    "members": [
      "Desh Acharjee",
      "Rayan Ferdous",
      "Sameer Mohammed Showkat",
      "Wali E Zaman"
    ]
  },
  {
    "team": "Belgium",
    "country": "BE",
    "members": [
      "Edward Rosseel",
      "Joaquim Schaeverbeke",
      "Noé Zech",
      "Thomas De Bruyn"
    ]
  },
  {
    "team": "Bolivia",
    "country": "BO",
    "members": [
      "Cristian Santiago Soto Cardona",
      "Gabriel Alberto Cruz Nogales",
      "Nestor Rafael Coronel Hurtado",
      "Nicolas Bravo"
    ]
  },
  {
    "team": "Bosnia and Herzegovina",
    "country": "BA",
    "members": [
      "Adnan Osmić",
      "Farah Demirović",
      "Faruk Demirović",
      "Mirza Bušatlić"
    ]
  },
  {
    "team": "Brazil",
    "country": "BR",
    "members": [
      "Enzo Ivamoto Hirota",
      "João Paulo Campos Oliveira",
      "Maria Clara Fontes Silva",
      "Pedro Suyama Leston Rey"
    ]
  },
  {
    "team": "Bulgaria",
    "country": "BG",
    "members": [
      "Aleksandar Pendov",
      "Andrey Stefanov",
      "Kiril Zulyamski",
      "Sava Delev"
    ]
  },
  {
    "team": "Canada",
    "country": "CA",
    "members": [
      "Alex Lin",
      "Haoyang Jin",
      "Jerry Zhou",
      "Nathan Katov"
    ]
  },
  {
    "team": "Chile",
    "country": "CL",
    "members": [
      "Frantz Quijano",
      "Nicolás Aballay Fernández",
      "Sofía Delorme",
      "Vicente Díaz"
    ]
  },
  {
    "team": "China",
    "country": "CN",
    "members": [
      "Jiawei Liu",
      "Qiwen Xu",
      "Shenghao Zhao",
      "Yuxiang He"
    ]
  },
  {
    "team": "Colombia",
    "country": "CO",
    "members": [
      "Camilo Cruz",
      "Mariana Molina",
      "Santiago Guaneme Quintero",
      "Tomás Torres"
    ]
  },
  {
    "team": "Costa Rica",
    "country": "CR",
    "members": [
      "André Jiménez",
      "Dylan Joel Laguna Arias",
      "Fabricio Arce",
      "Ignacio Carmiol"
    ]
  },
  {
    "team": "Croatia",
    "country": "HR",
    "members": [
      "Dino Hadžić",
      "Ivo Pavicic",
      "Lovro Tunjić",
      "Masa Dobric"
    ]
  },
  {
    "team": "Cuba",
    "country": "CU",
    "members": [
      "Fernando Jose Joa Cruz",
      "Maité Morales Carreras",
      "Mauricio Cruz Siles",
      "Zaniel García Orihuela"
    ]
  },
  {
    "team": "Cyprus",
    "country": "CY",
    "members": [
      "Aleksis Tsangaris",
      "Alexander Minko",
      "Mariza Paspalli",
      "Sofoclis Andronicou"
    ]
  },
  {
    "team": "Czech Republic",
    "country": "CZ",
    "members": [
      "Adam Houdek",
      "Erik Ježek",
      "Hugo Herynek",
      "Svatava Šimečková"
    ]
  },
  {
    "team": "Denmark",
    "country": "DK",
    "members": [
      "Andreas Vase Haraldsson",
      "Elias Gjedde-Grundtvig",
      "Marius Vilhelmsen",
      "Sigurd Jønch-Clausen"
    ]
  },
  {
    "team": "Dominican Republic",
    "country": "DO",
    "members": [
      "Adriano Augusto Hernández Rodríguez",
      "Baldwin Huang",
      "Yegor Afanaseva"
    ]
  },
  {
    "team": "Ecuador",
    "country": "EC",
    "members": [
      "Felipe Rivera",
      "Israel Zhu",
      "Matteo Calle",
      "Roberto Valverde Abad"
    ]
  },
  {
    "team": "Egypt",
    "country": "EG",
    "members": [
      "Ahmed Osman",
      "Ahmed Solyman",
      "Albaraa Ahmed",
      "Moez Mahmoud"
    ]
  },
  {
    "team": "El Salvador",
    "country": "SV",
    "members": [
      "Alexia Hernández",
      "German Santos",
      "Karla Ayala",
      "Sofia Gonzalez"
    ]
  },
  {
    "team": "Estonia",
    "country": "EE",
    "members": [
      "Agnes Tennisberg",
      "Kristjan Lepp",
      "Mattias Joosep Tammaru",
      "Rain Martin Ohlau"
    ]
  },
  {
    "team": "Finland",
    "country": "FI",
    "members": [
      "Aatu Kajasto",
      "Matias Sjölund",
      "Mikael Myllymäki",
      "Zhongyi Li"
    ]
  },
  {
    "team": "France",
    "country": "FR",
    "members": [
      "Daniil Jarykaou",
      "Hao-Yuan Jiao",
      "Joachim Bienvenüe",
      "Raphaël Pons"
    ]
  },
  {
    "team": "Georgia",
    "country": "GE",
    "members": [
      "Andria Vasadze",
      "Mate Rekhviashvili",
      "Nikoloz Melikishvili",
      "Vladimeri Prangishvili"
    ]
  },
  {
    "team": "Germany",
    "country": "DE",
    "members": [
      "Hans Sihan Zhu",
      "Maksym Shvedchenko",
      "Pascal Atzler",
      "Rasmus Zenker"
    ]
  },
  {
    "team": "Ghana",
    "country": "GH",
    "members": [
      "Alexandra Didieye",
      "Ernest Ampem",
      "Patrick Oscar Mmireku"
    ]
  },
  {
    "team": "Greece",
    "country": "GR",
    "members": [
      "Anna Kotoula",
      "Lazaros Karageorgiou",
      "Spyridon Alivizatos",
      "Theodoros Sarras"
    ]
  },
  {
    "team": "Hong Kong, China",
    "country": "HK",
    "members": [
      "Adam Xu",
      "Chun Hin Ivan Mak",
      "Ting Wai Lo",
      "Tsz Chai Berton Choy"
    ]
  },
  {
    "team": "Hungary",
    "country": "HU",
    "members": [
      "Balázs Szilágyi",
      "Gergely Sánta",
      "Horka Fajszi",
      "Zsolt Mihály"
    ]
  },
  {
    "team": "Iceland",
    "country": "IS",
    "members": [
      "Eysteinn Daði Hjaltason",
      "Gunnsteinn Þór Ólason",
      "Merkúr Máni Hermannsson",
      "Róbert Kristian Freysson"
    ]
  },
  {
    "team": "India",
    "country": "IN",
    "members": [
      "Aviansh Verma",
      "Naman Singh",
      "Neev Kataria",
      "Samik Goyal"
    ]
  },
  {
    "team": "Indonesia",
    "country": "ID",
    "members": [
      "Aufan Ahmad Mumtaza",
      "Franklin Filbert Irwan",
      "Nathan Allan",
      "Warren Xing"
    ]
  },
  {
    "team": "Iran",
    "country": "IR",
    "members": [
      "Arash Ostadsharif Memar",
      "Bahamin Shafaghi",
      "Hamed Ghaffariaghdas",
      "Mohammad Shayan"
    ]
  },
  {
    "team": "Ireland",
    "country": "IE",
    "members": [
      "Afric Deasy",
      "Ben Maguire",
      "Mykyta Telychko",
      "Séamas Riordan"
    ]
  },
  {
    "team": "Italy",
    "country": "IT",
    "members": [
      "Marco Gambaro",
      "Matteo Artale",
      "Nicola Dindo",
      "Sofia Maragò"
    ]
  },
  {
    "team": "Japan",
    "country": "JP",
    "members": [
      "Keisuke Kakehi",
      "Rei Karashima",
      "Yusa Kimura",
      "Yuya Hirasawa"
    ]
  },
  {
    "team": "Jordan",
    "country": "JO",
    "members": [
      "Ali Tahboub",
      "Meral Ahmad",
      "Qais Hanandeh",
      "Ramiz Hammad"
    ]
  },
  {
    "team": "Kazakhstan",
    "country": "KZ",
    "members": [
      "Akezhan Askar",
      "Aldiyar Seitbay",
      "Mansur Mamadakhunov",
      "Maxim Tsoy"
    ]
  },
  {
    "team": "Kyrgyzstan",
    "country": "KG",
    "members": [
      "Abdullahan Abdirasulov",
      "Alihan Aidarbekov",
      "Ian Bobrus",
      "Ramazan Mananov"
    ]
  },
  {
    "team": "Latvia",
    "country": "LV",
    "members": [
      "Edgars Andersons",
      "Jelizaveta Deņisova",
      "Kārlis Cīmurs",
      "Ričards Jansons"
    ]
  },
  {
    "team": "Libya",
    "country": "LY",
    "members": [
      "Abd Alraheem Miftah",
      "Abdulrauf Zayid",
      "Albara Abdulhafith",
      "Fadel Elsenusi"
    ]
  },
  {
    "team": "Lithuania",
    "country": "LT",
    "members": [
      "Adomas Juodis",
      "Augustas Kerys",
      "Faustas Surplys",
      "Robertas Juknevičius"
    ]
  },
  {
    "team": "Luxembourg",
    "country": "LU",
    "members": [
      "Adrian Mai",
      "Alex Avila González",
      "Sophie Zeihen",
      "Tudor Păltănea"
    ]
  },
  {
    "team": "Macao, China",
    "country": "MO",
    "members": [
      "Cheng Hou Tang",
      "Hang Chi Ng",
      "Hoi Xu",
      "Ziyan Wang"
    ]
  },
  {
    "team": "Malaysia",
    "country": "MY",
    "members": [
      "Isaac Kai Sheng Hew",
      "Janson Ho",
      "Yan Xun Khor",
      "Yuichiro Furuse"
    ]
  },
  {
    "team": "Mexico",
    "country": "MX",
    "members": [
      "Diego Francisco Martin Zárate",
      "Emmanuel Buenrostro Briseño",
      "José Andrés Lemus Velazquez",
      "Joseph Jael Tenorio Canul"
    ]
  },
  {
    "team": "Moldova",
    "country": "MD",
    "members": [
      "Alexei Baca",
      "Alin Popescu",
      "Anastasia Corsac",
      "Oleg Rața"
    ]
  },
  {
    "team": "Mongolia",
    "country": "MN",
    "members": [
      "Erkhem Ganzorig",
      "Erkhem Ganzorig",
      "Munkh-Erdene Bayarjargal",
      "Munkhtur Erdenebat"
    ]
  },
  {
    "team": "Montenegro",
    "country": "ME",
    "members": [
      "Balsa Radulovic"
    ]
  },
  {
    "team": "Morocco",
    "country": "MA",
    "members": [
      "Mohamed Aada",
      "Mohammed Cherki",
      "Yassir Salama",
      "Zakaria Abisourour"
    ]
  },
  {
    "team": "Netherlands",
    "country": "NL",
    "members": [
      "Gideon Beerens",
      "Jelte Loeve",
      "Karel Hofman",
      "Niek van Delft"
    ]
  },
  {
    "team": "New Zealand",
    "country": "NZ",
    "members": [
      "Boliang Liu",
      "Juno Rainey",
      "Peter Zhou",
      "Xuan Li"
    ]
  },
  {
    "team": "Nigeria",
    "country": "NG",
    "members": [
      "Agbo Adoga",
      "Hallel Okpere Udo",
      "Nnabugo Ofordile",
      "Onyeka Chukwuji"
    ]
  },
  {
    "team": "North Macedonia",
    "country": "MK",
    "members": [
      "Damjan Davkov",
      "Nikola Stojkovski",
      "Viktor Maksimoski",
      "Vladimir Grchev"
    ]
  },
  {
    "team": "Norway",
    "country": "NO",
    "members": [
      "Aleksandra Streltsova",
      "Daniel Alex Mineev",
      "Ivar Lee Fevang",
      "Julian Berg-Larsen"
    ]
  },
  {
    "team": "Pakistan",
    "country": "PK",
    "members": [
      "Faisal Saqib",
      "Jawad Akbar",
      "Muhammad Aneeq",
      "Muhammad Saram"
    ]
  },
  {
    "team": "Palestine",
    "country": "PS",
    "members": [
      "Abdallah Sherbini",
      "Kareem Kayid",
      "Mohammed Kurd"
    ]
  },
  {
    "team": "Peru",
    "country": "PE",
    "members": [
      "Daniel Pocohuanca",
      "Hector Edwardo Medrano Quispe",
      "Hector Tenorio Rodriguez",
      "Sebastian Estela"
    ]
  },
  {
    "team": "Philippines",
    "country": "PH",
    "members": [
      "EdRonn James Panti",
      "Jerome Austin Te",
      "Lorenz Nunez",
      "Prince Dela Cruz"
    ]
  },
  {
    "team": "Poland",
    "country": "PL",
    "members": [
      "Artur Smoleński",
      "Franciszek Szymula",
      "Krzysztof Witkowski",
      "Stanisław Lada"
    ]
  },
  {
    "team": "Portugal",
    "country": "PT",
    "members": [
      "Anton Gavrilov",
      "David Montenegro",
      "Luís Dias",
      "Luís Morais"
    ]
  },
  {
    "team": "Republic of Korea",
    "country": "KR",
    "members": [
      "Jaewon Son",
      "Jaewoo Byun",
      "Min-chan Jung",
      "Seungmin Yang"
    ]
  },
  {
    "team": "Romania",
    "country": "RO",
    "members": [
      "Alexandru Dima",
      "Andrei-Paul Iorgulescu",
      "Mihai-Valeriu Voicu",
      "Rareș-Andrei Neculau"
    ]
  },
  {
    "team": "Rwanda",
    "country": "RW",
    "members": [
      "Amandine Kaneza",
      "Baraka Mulwa",
      "Barnabe Abumugisha",
      "Happy David"
    ]
  },
  {
    "team": "Saudi Arabia",
    "country": "SA",
    "members": [
      "Altayeb Alakhdhari",
      "Mohammed Alasmari",
      "Saad Alarifi",
      "Sultan Alaiban"
    ]
  },
  {
    "team": "Serbia",
    "country": "RS",
    "members": [
      "Nikola Šami",
      "Pavle Damjanović",
      "Petar Banović",
      "Stefan Šebez"
    ]
  },
  {
    "team": "Singapore",
    "country": "SG",
    "members": [
      "Derrick Lukimin",
      "Jayden Hoo Dun Jie",
      "Simiao Gu",
      "Yi Xiang Tey"
    ]
  },
  {
    "team": "Slovakia",
    "country": "SK",
    "members": [
      "Marián Kovaľ",
      "Matej Bachniček",
      "Richard Dudek",
      "Viliam Gottweis"
    ]
  },
  {
    "team": "Slovenia",
    "country": "SI",
    "members": [
      "Luka Heric",
      "Primož Markovič",
      "Taras Vuk",
      "Vid Furlan"
    ]
  },
  {
    "team": "South Africa",
    "country": "ZA",
    "members": [
      "David Eyal",
      "Frederick Senekal",
      "Nico Schreuder",
      "Youkyum Kim"
    ]
  },
  {
    "team": "Spain",
    "country": "ES",
    "members": [
      "Andrii Basov",
      "Daniel Carpenter",
      "David Lago Alonso",
      "Guillem Vizcarro"
    ]
  },
  {
    "team": "Sri Lanka",
    "country": "LK",
    "members": [
      "Praveen Athauda-Arachchi",
      "Ravindu Ranathunga",
      "Sandayuru Sanahas",
      "Yasiru Hasantha"
    ]
  },
  {
    "team": "Sweden",
    "country": "SE",
    "members": [
      "Anastasiia Saranchina",
      "Erik Adebahr",
      "Simon Persson Holm",
      "Vladyslav Levchenko"
    ]
  },
  {
    "team": "Switzerland",
    "country": "CH",
    "members": [
      "Andrej Ševera",
      "Laetitia Orglmeister",
      "Myriam Faltin",
      "Yuhua Su"
    ]
  },
  {
    "team": "Syria",
    "country": "SY",
    "members": [
      "Ghassan Hasan",
      "Hadi Suleiman",
      "Ibrahem Fostok",
      "Mohamad Adeeb Obeido"
    ]
  },
  {
    "team": "Taiwan",
    "country": "TW",
    "members": [
      "Chi-You Lin",
      "Po-Ting Li",
      "Yu-Hsiang Liao",
      "Yu-Lun Huang"
    ]
  },
  {
    "team": "Tajikistan",
    "country": "TJ",
    "members": [
      "Abubakr Nuralizoda",
      "Alijon Odilov",
      "Anri Esoev",
      "Azam Rakhimov"
    ]
  },
  {
    "team": "Thailand",
    "country": "TH",
    "members": [
      "Araya Luanseng",
      "Pakin Olanraktham",
      "Pattarakorn Sutthajunya",
      "Thanabodhi Sihsobhon"
    ]
  },
  {
    "team": "Tunisia",
    "country": "TN",
    "members": [
      "Ahmed Kaaniche",
      "Amine Manai",
      "Meriam Louzi",
      "Omar Allouch"
    ]
  },
  {
    "team": "Türkiye",
    "country": "TR",
    "members": [
      "Ahmet Alp Orakçı",
      "Ahmet Emre Gürdal",
      "Noyan Cantürk",
      "Yunus Emre Artal"
    ]
  },
  {
    "team": "Ukraine",
    "country": "UA",
    "members": [
      "Daria Lobas",
      "Daria Perekopska",
      "Illia Shevchenko",
      "Vladyslav Khalin"
    ]
  },
  {
    "team": "United Kingdom",
    "country": "GB",
    "members": [
      "Adavya Goyal",
      "Anango Prabhat",
      "Isane Sekiguchi",
      "Xingzhi Lu"
    ]
  },
  {
    "team": "United States of America",
    "country": "US",
    "members": [
      "Jason Sun",
      "Jonathan He",
      "Kai Jiang",
      "Nelson Huang"
    ]
  },
  {
    "team": "Uzbekistan",
    "country": "UZ",
    "members": [
      "Jahongir Shoh Avazkhonov",
      "Jakhonali Khaydaraliev",
      "Timur Kadirbergenov",
      "Ulug&#039;bek Rakhmatullaev"
    ]
  },
  {
    "team": "Uzbekistan 2",
    "country": "UZ",
    "members": [
      "Humoyun Abduraupov",
      "Ravshan Rahmiddinov",
      "Sardor Salimov",
      "Ulugbek Kamalov"
    ]
  },
  {
    "team": "Venezuela",
    "country": "VE",
    "members": [
      "Alejandro José González Salazar",
      "Antonella Alejandra González Salazar",
      "Isabel Patricia Rivas Morantes",
      "Jesús Alejandro Aguirre Vasquez"
    ]
  },
  {
    "team": "Vietnam",
    "country": "VN",
    "members": [
      "Dung Nguyen Bui Duc",
      "Hau Dang Huy",
      "Phuc Nguyen Khanh",
      "Tuan Nguyen Huu"
    ]
  },
  {
    "team": "IOI team",
    "country": null,
    "members": [
      "Akmuhammet Shohratgeldiyev",
      "Amir Krispin",
      "Daniel Priness",
      "Fiodar Sashko",
      "Henadzi Martsinkevich",
      "Hojamuhammet Hydyrov",
      "Jalaladdin Nargulyyev",
      "Kasym Kochekov",
      "Kiryl Kardash",
      "Maksim Kravchenko",
      "Mikhail Brel",
      "Sergei Mukhanov",
      "Vladimir Zvezdin",
      "Vladislav Zhiganov",
      "Yoav Shamay",
      "Yotam Budnik"
    ]
  }
];
