/**
 * Regenerates src/lib/ioi-contestants.ts from the IOI statistics site.
 *
 * Usage: pnpm exec tsx scripts/gen-ioi-contestants.ts [year]
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";

const YEAR = process.argv[2] ?? "2026";
const URL = `https://stats.ioinformatics.org/contestants/${YEAR}`;

/** ISO 3166-1 alpha-3 -> alpha-2 (countries that participate in the IOI). */
const A3_TO_A2: Record<string, string> = {
  ALB: "AL", ARG: "AR", ARM: "AM", AUS: "AU", AUT: "AT", AZE: "AZ",
  BEL: "BE", BGD: "BD", BGR: "BG", BIH: "BA", BLR: "BY", BOL: "BO",
  BRA: "BR", BRN: "BN", CAN: "CA", CHE: "CH", CHL: "CL", CHN: "CN",
  COL: "CO", CRI: "CR", CUB: "CU", CYP: "CY", CZE: "CZ", DEU: "DE",
  DNK: "DK", DOM: "DO", DZA: "DZ", ECU: "EC", EGY: "EG", ESP: "ES",
  EST: "EE", ETH: "ET", FIN: "FI", FRA: "FR", GBR: "GB", GEO: "GE",
  GHA: "GH", GRC: "GR", GTM: "GT", HKG: "HK", HND: "HN", HRV: "HR",
  HUN: "HU", IDN: "ID", IND: "IN", IRL: "IE", IRN: "IR", IRQ: "IQ",
  ISL: "IS", ISR: "IL", ITA: "IT", JAM: "JM", JOR: "JO", JPN: "JP",
  KAZ: "KZ", KEN: "KE", KGZ: "KG", KHM: "KH", KOR: "KR", KWT: "KW",
  LAO: "LA", LBN: "LB", LBY: "LY", LIE: "LI", LKA: "LK", LTU: "LT",
  LUX: "LU", LVA: "LV", MAC: "MO", MAR: "MA", MDA: "MD", MDG: "MG",
  MEX: "MX", MKD: "MK", MLT: "MT", MNE: "ME", MNG: "MN", MYS: "MY",
  NGA: "NG", NLD: "NL", NOR: "NO", NPL: "NP", NZL: "NZ", PAK: "PK",
  PAN: "PA", PER: "PE", PHL: "PH", POL: "PL", PRT: "PT", PRY: "PY",
  PSE: "PS", ROU: "RO", RUS: "RU", RWA: "RW", SAU: "SA", SGP: "SG",
  SLV: "SV", SRB: "RS", SVK: "SK", SVN: "SI", SWE: "SE", SYR: "SY",
  THA: "TH", TJK: "TJ", TKM: "TM", TUN: "TN", TUR: "TR", TWN: "TW",
  UKR: "UA", URY: "UY", USA: "US", UZB: "UZ", VEN: "VE", VNM: "VN",
  ZAF: "ZA", ZWE: "ZW",
};

type Team = { team: string; country: string | null; members: string[] };

async function main() {
  const res = await fetch(URL);
  if (!res.ok) throw new Error(`GET ${URL} -> ${res.status}`);
  const html = await res.text();

  const teams: Team[] = [];
  let current: Team | null = null;
  for (const row of html.matchAll(/<tr>([\s\S]*?)<\/tr>/g)) {
    const tr = row[1];
    if (tr.includes("<th")) continue;
    const countryMatch = tr.match(/<a href="countries\/([A-Z]*)">([^<]*)<\/a>/);
    if (countryMatch) {
      const [, a3, teamName] = countryMatch;
      const isIoiTeam = !a3 && !teamName;
      if (a3 && !A3_TO_A2[a3]) throw new Error(`unmapped country code ${a3}`);
      current = {
        team: isIoiTeam ? "IOI team" : teamName,
        country: a3 ? A3_TO_A2[a3] : null,
        members: [],
      };
      teams.push(current);
    }
    const person = tr.match(/<a href="people\/\d+">([^<]+)<\/a>/);
    if (person && current) current.members.push(person[1]);
  }

  const total = teams.reduce((n, t) => n + t.members.length, 0);
  if (total < 100) throw new Error(`only parsed ${total} contestants — page format changed?`);

  const out = `/**
 * IOI ${YEAR} contestants grouped by team, from ${URL}.
 * Generated by scripts/gen-ioi-contestants.ts — do not edit by hand.
 */
export type IoiTeam = { team: string; country: string | null; members: string[] };

export const IOI_TEAMS: IoiTeam[] = ${JSON.stringify(teams, null, 2)};
`;
  const dest = join(__dirname, "..", "src", "lib", "ioi-contestants.ts");
  writeFileSync(dest, out);
  console.log(`wrote ${teams.length} teams / ${total} contestants to ${dest}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
